### ISSUE TITLE
séparer les restau 🍽️  de `Mnomnom 🍔`

### ISSUE THREAD

**Issue by arieloO** [tlenclos/joli-mapstr#5]
![Capture d’écran 2022-08-08 à 16 11 56](https://user-images.githubusercontent.com/33434462/183438603-95baf498-cc93-4ec1-b50f-5ca653c9510b.png)

**Comment by tlenclos** [comment]
Plutôt via l'utilisation de tag non ?

**Comment by lyrixx** [comment]
j'ai implément ça dans #13 ; j'ai pris une autre décision que les deux propositions :) 

1. séparer, c'est pas pratique car y'a des candidats qui peuvent aller dans les deux parties (d'ailleurs, c'est aussi le cas avec Bar & Resto !)
2. Les tags c'est pas pratique, car une typo est si vite arrivé ! du coup y'a deux nouveaux champs `onPremise` & `takeaway` qu'on peut renseigner sans le JSON.
